name: Deploy
on:
  push:
    branches:
      - "main"
  workflow_dispatch: {}
permissions:
  id-token: write
  contents: read
jobs:
  S3FileUpload:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_S3_ROLE }}
          role-session-name: cicd-session
          aws-region: ${{ secrets.AWS_S3_REGION }}
      - name: Upload file
        run: |
          aws s3 cp ./src/index.html s3://${{ secrets.AWS_S3_NAME }}/index.html
